### ISSUE TITLE
Using bucklescript namespace

### ISSUE THREAD

**Issue by zaaack** [bloodyowl/reReactPrimitives#12]
https://bucklescript.github.io/bucklescript/Manual.html#_namespace_support_since_1_9_0

**Comment by bloodyowl** [comment]
i'm currently having some issues internally with bucklescript@1.9.0
I'll add it when I figured out what's happening 😄

in the meantime, would a `ReReactPrimitives` module exporting all the components work for you to help with the transition?

**Comment by zaaack** [comment]
@bloodyowl Actually this is just an adwise, I'm still getting familiar with reason and working on an small demo. So thanks for your concern and I'm not really need it for now😅.

**Comment by MoOx** [comment]
Time to think about it :)
